apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nmgb732sy-go
  janus-idp.io/tekton: nmgb732sy-go
  backstage.io/kubernetes-id: nmgb732sy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmgb732sy-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
