apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nmgb732sy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nmgb732sy-go 
  name: nmgb732sy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nmgb732sy-go 
